title: Home Assistant Solis Automations
description: Automations & Lovelace cards for Solis (Solar) inverter – Modbus, battery reserve, grid planned outages (YAML).
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
