alias: ESO – sukurti įvykį iš kortelės
description: ""
triggers:
  - entity_id: input_button.eso_sukurti
    trigger: state
conditions:
  - condition: template
    value_template: |-
      {{ as_datetime(states('input_datetime.eso_pradzia'))
         < as_datetime(states('input_datetime.eso_pabaiga')) }}
actions:
  - target:
      entity_id: calendar.eso_planiniai_darbai
    data:
      summary: "{{ states('input_text.eso_pavadinimas') or 'ESO atjungimas' }}"
      start_date_time: "{{ states('input_datetime.eso_pradzia') }}"
      end_date_time: "{{ states('input_datetime.eso_pabaiga') }}"
      description: Planinis ESO atjungimas (sukurta iš kortelės)
    action: calendar.create_event
mode: single
