alias: Akumuliatorių įkrovimas nuo saulės – dienos logika
triggers:
  - at: "05:00:00"
    id: new_day
    trigger: time
  - id: soc_threshold_reached
    value_template: |
      {{ states('sensor.solis_waveshare_battery_soc')|float(0)
         >= (states('sensor.solis_waveshare_backup_soc')|float(0) + 10) }}
    trigger: template
  - id: battery_full
    entity_id: sensor.solis_waveshare_battery_soc
    above: 99.9
    for:
      minutes: 1
    trigger: numeric_state
  - at: input_datetime.reakcija_i_laika
    id: time_cutoff
    trigger: time
conditions:
  - condition: state
    entity_id: input_boolean.ziemos_rezimas_elektrinei
    state: "off"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: new_day
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{
                      states('sensor.solcast_pv_forecast_forecast_today')|float(0)
                         < states('input_number.reakcija_i_gamybos_prognoze')|float(0) }}
                sequence:
                  - target:
                      entity_id: switch.feed_in_priority_mode
                    action: switch.turn_off
              - conditions:
                  - condition: template
                    value_template: >
                      {{
                      states('sensor.solcast_pv_forecast_forecast_today')|float(0)
                         > states('input_number.reakcija_i_gamybos_prognoze')|float(0) }}
                  - condition: template
                    value_template: >
                      {{
                      states('sensor.solcast_pv_forecast_peak_forecast_today')|float(0)
                         > states('input_number.reakcija_i_dienos_max_generacija')|float(0) }}
                sequence:
                  - target:
                      entity_id: switch.feed_in_priority_mode
                    action: switch.turn_on
              - conditions:
                  - condition: template
                    value_template: >
                      {{
                      states('sensor.solcast_pv_forecast_forecast_today')|float(0)
                         > states('input_number.reakcija_i_gamybos_prognoze')|float(0) }}
                  - condition: template
                    value_template: >
                      {{
                      states('sensor.solcast_pv_forecast_peak_forecast_today')|float(0)
                         < states('input_number.reakcija_i_dienos_max_generacija')|float(0) }}
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: >
                              {{
                              states('sensor.solis_waveshare_battery_soc')|float(0)
                                 >= (states('sensor.solis_waveshare_backup_soc')|float(0) + 10) }}
                        sequence:
                          - target:
                              entity_id: switch.feed_in_priority_mode
                            action: switch.turn_on
                    default:
                      - target:
                          entity_id: switch.feed_in_priority_mode
                        action: switch.turn_off
  - choose:
      - conditions:
          - condition: trigger
            id: battery_full
        sequence:
          - target:
              entity_id: switch.feed_in_priority_mode
            action: switch.turn_off
  - choose:
      - conditions:
          - condition: trigger
            id: time_cutoff
          - condition: numeric_state
            entity_id: sensor.solis_waveshare_battery_soc
            below: 100
        sequence:
          - target:
              entity_id: switch.feed_in_priority_mode
            action: switch.turn_off
  - choose:
      - conditions:
          - condition: trigger
            id: soc_threshold_reached
          - condition: template
            value_template: |
              {{ states('sensor.solcast_pv_forecast_forecast_today')|float(0)
                 > states('input_number.reakcija_i_gamybos_prognoze')|float(0) }}
          - condition: template
            value_template: >
              {{
              states('sensor.solcast_pv_forecast_peak_forecast_today')|float(0)
                 < states('input_number.reakcija_i_dienos_max_generacija')|float(0) }}
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    before: "12:00:00"
                sequence:
                  - target:
                      entity_id: switch.feed_in_priority_mode
                    action: switch.turn_on
            default:
              - target:
                  entity_id: switch.feed_in_priority_mode
                action: switch.turn_off
mode: single

