alias: Žiemos režimo rezervas – Backup SOC ir Reserve Mode
mode: restart

trigger:
  - platform: state
    entity_id: input_boolean.ziemos_rezimas_elektrinei
    to: "on"
    id: winter_on

  - platform: state
    entity_id: input_boolean.ziemos_rezimas_elektrinei
    to: "off"
    id: winter_off

  - platform: state
    entity_id:
      - input_number.akumuliatoriaus_rezervavimas
      - input_number.akumuliatoriaus_rezervavimas_vasarai
    id: reserve_numbers_changed

  - platform: homeassistant
    event: start
    id: hass_start

condition:
  - condition: state
    entity_id: input_boolean.akumuliatoriu_rankinis_rezervavimas
    state: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: winter_on
        sequence:
          # Snapshot helper'is: įrašom, ar switch buvo ON tuo momentu
          - choose:
              - conditions:
                  - condition: state
                    entity_id: switch.reserve_battery_mode
                    state: "on"
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.reserve_battery_mode_before_winter
            default:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.reserve_battery_mode_before_winter

          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas')|float(0) }}"

          - service: switch.turn_off
            target:
              entity_id: switch.feed_in_priority_mode

          - service: switch.turn_on
            target:
              entity_id: switch.reserve_battery_mode

      - conditions:
          - condition: trigger
            id: winter_off
        sequence:
          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas_vasarai')|float(0) }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.reserve_battery_mode_before_winter
                    state: "on"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: switch.reserve_battery_mode
            default:
              - service: switch.turn_off
                target:
                  entity_id: switch.reserve_battery_mode

      - conditions:
          - condition: trigger
            id: reserve_numbers_changed
          - condition: state
            entity_id: input_boolean.ziemos_rezimas_elektrinei
            state: "on"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas')|float(0) }}"
          - service: switch.turn_on
            target:
              entity_id: switch.reserve_battery_mode

      - conditions:
          - condition: trigger
            id: reserve_numbers_changed
          - condition: state
            entity_id: input_boolean.ziemos_rezimas_elektrinei
            state: "off"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas_vasarai')|float(0) }}"

      - conditions:
          - condition: trigger
            id: hass_start
          - condition: state
            entity_id: input_boolean.ziemos_rezimas_elektrinei
            state: "on"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas')|float(0) }}"
          - service: switch.turn_off
            target:
              entity_id: switch.feed_in_priority_mode
          - service: switch.turn_on
            target:
              entity_id: switch.reserve_battery_mode

      - conditions:
          - condition: trigger
            id: hass_start
          - condition: state
            entity_id: input_boolean.ziemos_rezimas_elektrinei
            state: "off"
        sequence:
          - service: number.set_value
            target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: "{{ states('input_number.akumuliatoriaus_rezervavimas_vasarai')|float(0) }}"

