alias: Grid – Create Event from Card
description: ""
triggers:
  - entity_id: input_button.grid_create_event
    trigger: state
conditions:
  - condition: template
    value_template: |-
      {{ as_datetime(states('input_datetime.grid_event_start'))
         < as_datetime(states('input_datetime.grid_event_end')) }}
actions:
  - target:
      entity_id: calendar.grid_planned_outages
    data:
      summary: "{{ states('input_text.grid_event_title') or 'Grid atjungimas' }}"
      start_date_time: "{{ states('input_datetime.grid_event_start') }}"
      end_date_time: "{{ states('input_datetime.grid_event_end') }}"
      description: Planned grid outage (sukurta iš kortelės)
    action: calendar.create_event
mode: single
