alias: Solar – Periodic Charging
description: " (žiemą iki 100%)"
triggers:
  - at: input_datetime.solar_charge_2_time
    trigger: time
conditions:
  - condition: state
    entity_id: input_boolean.solar_winter_mode
    state: "on"
  - condition: template
    value_template: >-
      {% set last = states('input_datetime.solar_charge_2_last_run')
      %} {% set interval =
      states('input_number.solar_charge_2_days_interval')|int(1) %} {% if
      last in ['unknown','unavailable',''] %}
        true
      {% else %}
        {% set d_last = as_datetime(last).date() %}
        {{ (now().date() - d_last).days >= interval }}
      {% endif %}
actions:
  - target:
      entity_id: switch.grid_time_of_use_charging_period_2
    action: switch.turn_on
  - target:
      entity_id: input_datetime.solar_charge_2_last_run
    data:
      date: "{{ now().date() }}"
    action: input_datetime.set_datetime
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.solis_waveshare_battery_soc')|float(0) >= 100 }}"
        sequence:
          - target:
              entity_id: switch.grid_time_of_use_charging_period_2
            action: switch.turn_off
    default:
      - wait_for_trigger:
          - value_template: "{{ states('sensor.solis_waveshare_battery_soc')|float(0) >= 100 }}"
            trigger: template
        continue_on_timeout: false
      - target:
          entity_id: switch.grid_time_of_use_charging_period_2
        action: switch.turn_off
mode: restart