alias: Battery Charging from Solar – Daytime Logic
triggers:
  - id: new_day
    at: "05:00:00"
    trigger: time
  - id: battery_full
    entity_id: sensor.solis_waveshare_battery_soc
    above: 99.9
    for:
      minutes: 1
    trigger: numeric_state
  - id: time_cutoff
    at: input_datetime.time_cutoff
    trigger: time
conditions:
  - condition: state
    entity_id: input_boolean.solar_winter_mode
    state: "off"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: new_day
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: sensor.solcast_pv_forecast_forecast_today
                    below: input_number.generation_forecast_threshold
                sequence:
                  - target:
                      entity_id: switch.feed_in_priority_mode
                    action: switch.turn_off
              - conditions:
                  - condition: and
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.solcast_pv_forecast_forecast_today
                        above: input_number.generation_forecast_threshold
                sequence:
                  - choose:
                      - conditions:
                          - condition: numeric_state
                            entity_id: sensor.solcast_pv_forecast_peak_forecast_today
                            below: input_number.daily_peak_generation_threshold
                        sequence:
                          - target:
                              entity_id: switch.feed_in_priority_mode
                            action: switch.turn_off
                      - conditions:
                          - condition: numeric_state
                            entity_id: sensor.solcast_pv_forecast_peak_forecast_today
                            above: input_number.daily_peak_generation_threshold
                        sequence:
                          - target:
                              entity_id: switch.feed_in_priority_mode
                            action: switch.turn_on
                    default: []
      - conditions:
          - condition: trigger
            id: battery_full
        sequence:
          - target:
              entity_id: switch.feed_in_priority_mode
            action: switch.turn_off
      - conditions:
          - condition: trigger
            id: time_cutoff
          - condition: numeric_state
            entity_id: sensor.solis_waveshare_battery_soc
            below: 100
        sequence:
          - target:
              entity_id: switch.feed_in_priority_mode
            action: switch.turn_off
    default: []
mode: single
