alias: Winter Mode Reserve – Backup SOC & Reserve Mode
triggers:
  - entity_id: input_boolean.solar_winter_mode
    trigger: state
  - entity_id:
      - input_number.battery_reserve
      - input_number.battery_reserve_summer
    trigger: state
  - event: start
    trigger: homeassistant
conditions:
  - condition: state
    entity_id: input_boolean.manual_battery_reserve
    state: "off"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.solar_winter_mode
            state: "on"
        sequence:
          - target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: >-
                {{ states('input_number.battery_reserve') |
                float(0) }}
            action: number.set_value
          - target:
              entity_id: switch.reserve_battery_mode
            action: switch.turn_on
      - conditions:
          - condition: state
            entity_id: input_boolean.solar_winter_mode
            state: "off"
        sequence:
          - target:
              entity_id: number.solis_waveshare_backup_soc
            data:
              value: >-
                {{ states('input_number.battery_reserve_summer') |
                float(0) }}
            action: number.set_value
          - target:
              entity_id: switch.reserve_battery_mode
            action: switch.turn_off
    default: []
mode: restart
